version: "3.9"
services:
  hanime-web:
    build: .
    container_name: hanime-web
    ports:
      - "3280:3280"
    restart: unless-stopped
    environment:
      - PORT=3280
      - ENGINE_URL=http://127.0.0.1:5001
      - ENGINE_PROXY=http://host.docker.internal:10808
    volumes:
      - ./downloads:/downloads
    extra_hosts:
      - "host.docker.internal:host-gateway"
